site:
  title: AgnosticLP
  start_page: docs:overview.adoc
content:
  #sources: $HOME//Users/valentinarodriguez/Documents/workspace/rhtr2020_pipelines/workshop/content
  sources: 
  - url: ../modules
    branches: branch-valen
    # setting edit_url to false disables the Edit this Page link for any page that originates from this repository
    # the same thing can be achieved by adding empty credentials (i.e., @) in front of the domain in the URL
ui:
  bundle:
    url: ../web_app/ui-bundle.zip
    snapshot: true
output:
  dir: ../web_app
